version: '3'

services:
  edentalist-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - edentalistappnet

    
  edentalist-api:
    restart: unless-stopped
    build:
        context: .
    environment:
      - ConnectionStrings:eDentalist=Server=edentalist-sql,1433;Database=160035Docker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 44311:80
    networks:
      - edentalistappnet
    links:
      - edentalist-sql
    depends_on:
      - edentalist-sql  
networks:
  edentalistappnet:
    driver: bridge